/* Generated By:JavaCC: Do not edit this line. MiniJavaScannerConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaScannerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int LETTER = 11;
  /** RegularExpression Id. */
  int CLASS = 12;
  /** RegularExpression Id. */
  int PUBLIC = 13;
  /** RegularExpression Id. */
  int STATIC = 14;
  /** RegularExpression Id. */
  int VOID = 15;
  /** RegularExpression Id. */
  int MAIN = 16;
  /** RegularExpression Id. */
  int LEFTBRACE = 17;
  /** RegularExpression Id. */
  int RIGHTBRACE = 18;
  /** RegularExpression Id. */
  int LEFTPAREN = 19;
  /** RegularExpression Id. */
  int RIGHTPAREN = 20;
  /** RegularExpression Id. */
  int LEFTBRACKET = 21;
  /** RegularExpression Id. */
  int RIGHTBRACKET = 22;
  /** RegularExpression Id. */
  int EXTENDS = 23;
  /** RegularExpression Id. */
  int RETURN = 24;
  /** RegularExpression Id. */
  int STRING = 25;
  /** RegularExpression Id. */
  int INT = 26;
  /** RegularExpression Id. */
  int BOOLEAN = 27;
  /** RegularExpression Id. */
  int ASSIGN = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int LT = 30;
  /** RegularExpression Id. */
  int PLUS = 31;
  /** RegularExpression Id. */
  int MINUS = 32;
  /** RegularExpression Id. */
  int MULT = 33;
  /** RegularExpression Id. */
  int DOT = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int EXCLAMATION = 36;
  /** RegularExpression Id. */
  int SEMICOLON = 37;
  /** RegularExpression Id. */
  int LENGTH = 38;
  /** RegularExpression Id. */
  int TRUE = 39;
  /** RegularExpression Id. */
  int FALSE = 40;
  /** RegularExpression Id. */
  int THIS = 41;
  /** RegularExpression Id. */
  int NEW = 42;
  /** RegularExpression Id. */
  int IF = 43;
  /** RegularExpression Id. */
  int ELSE = 44;
  /** RegularExpression Id. */
  int WHILE = 45;
  /** RegularExpression Id. */
  int PRINT = 46;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 47;
  /** RegularExpression Id. */
  int IDENTIFIER = 48;
  /** RegularExpression Id. */
  int ERROR = 49;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\" \"",
    "\"\\b\"",
    "\"\\f\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "<DIGIT>",
    "<LETTER>",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"extends\"",
    "\"return\"",
    "\"String\"",
    "\"int\"",
    "\"boolean\"",
    "\"=\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\".\"",
    "\",\"",
    "\"!\"",
    "\";\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"System.out.println\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "<ERROR>",
  };

}
